# Generated by Django 4.2.10 on 2024-02-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee", name="biography", field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="city",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="experience_level",
            field=models.CharField(
                choices=[("Junior", "Junior"), ("Mid", "Mid"), ("Senior", "Senior")],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="national_id",
            field=models.IntegerField(null=True),
        ),
    ]
