# Generated by Django 4.2.10 on 2024-02-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="jobs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("Junior", "Junior"),
                            ("Mid", "Mid"),
                            ("Senior", "Senior"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
            ],
        ),
    ]
