# Generated by Django 4.2.10 on 2024-02-09 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_alter_jobs_employer"),
    ]

    operations = [
        migrations.DeleteModel(name="jobs",),
    ]
