# Generated by Django 4.2.10 on 2024-02-09 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_employer"),
        ("jobs", "0005_delete_jobs"),
    ]

    operations = [
        migrations.CreateModel(
            name="Jobs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("Junior", "Junior"),
                            ("Mid", "Mid"),
                            ("Senior", "Senior"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "employer",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.employer",
                    ),
                ),
            ],
        ),
    ]
